# Generated by Django 6.0.5 on 2026-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nre", models.CharField(max_length=11, unique=True)),
                ("naran_aluno", models.CharField(max_length=200)),
                ("hela_fatin", models.CharField(max_length=50)),
                ("nu_telefone", models.CharField(max_length=11)),
            ],
        ),
    ]
