# Generated by Django 6.0.5 on 2026-05-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_dep", models.CharField(max_length=10, unique=True)),
                ("naran_dep", models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name="estudante",
            name="nu_telefone",
        ),
        migrations.AddField(
            model_name="estudante",
            name="data_moris",
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estudante",
            name="email",
            field=models.EmailField(default="default@email.com", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estudante",
            name="idade",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estudante",
            name="sexu",
            field=models.CharField(
                choices=[("Mane", "Mane"), ("Feto", "Feto")],
                default="Mane",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="estudante",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="hela_fatin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="estudante",
            name="naran_dep",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="App.departamento",
            ),
            preserve_default=False,
        ),
    ]
