# Generated by Django 6.0.5 on 2026-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_departamento_remove_estudante_nu_telefone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="naran_dep",
            field=models.CharField(max_length=80),
        ),
    ]
